Exercícios do capítulo um 🌻
maltexto/Learn4Elixir pull request #1
Opened 2023-10-09 03:14 UTC by maltexto

### Solução do Livebook Nº {numero da lição}
🌻
cc @anabastos @camilotk @cherryramatisdev @cyytrus @digzom @douglastofoli @eulixir @lanjoni @OtavioSC @zoedsoupe

2023-10-10 14:55 UTC, OtavioSC requested changes
Parabéns pelo esforço, os demais exercícios estão corretos, só faltando ajustar essa última questão.
Não esqueça de adicionar a tag da Hacktoberfest na PR para ocorrer a validação após o merge.

2023-10-15 21:50 UTC, maltexto commented on chapters/chapter1.livemd
> +  defstruct [:nome, :superficie, :volume, :massa, :temp_media, :distancia_sol]
Feito ✅

2023-10-16 12:42 UTC, OtavioSC commented
Muito bom, parabéns 🎉

2023-10-16 12:42 UTC, OtavioSC approved these changes

2023-10-16 13:27 UTC, merged